### ISSUE TITLE
Could you package this lib to npm?

### ISSUE THREAD

**Issue by jingliancui** [Baizey/ts-dependency-injection#3]
So that i can update it through npm.

**Comment by Baizey** [comment]
Hi, it is actually available on npm, although the name sadly isnt 1-1 with the repository name

https://www.npmjs.com/package/sharp-dependency-injection

I even have a full ci/cd pipeline for testing and automatically publishing new versions :)

**Comment by jingliancui** [comment]
OK. Thanks so much!
